server:
   port: 8880

#
# git based
#
spring:
   cloud:
      config:
         server:
            encrypt.enabled: false
            git:
               uri: https://github.com/kickscar/msa-practices/service-config-repo/

  
#
# file-system based(native)
#
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file:///Users/kickscar/DoWork/STS-Workspace/msa-practices/service-configs/service-emaillist