# spring configuration
spring:
   application:
      name: service-emaillist
   profiles:
      active: development


---
# configuration: common
spring:
   cloud:
      config:
         enabled: true
         uri: http://localhost:7777


---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777
    
                            
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.172:7777

      
---
# configuration: test
spring:
   config:
      activate:
         on-profile: test
         
   cloud:
      config:
         enabled: false

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

   security:
      oauth2:
         resourceserver:
           jwt:
              issuer-uri: http://localhost:5555/realms/poscodx2023-realm
              jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs         
                      