# spring configuration
spring:
   application:
      name: service-emaillist
   profiles:
      active: development


---
# configuration: common
spring:
   cloud:
      config:
         enabled: true
         uri: http://localhost:7777


---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777
    
                            
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.172:7777

      
---
# configuration: test
spring:
   config:
      activate:
         on-profile: test
         
   cloud:
      config:
         enabled: false
                  
   security:
      oauth2:
         client:
            registration:
               keyclock:
                  client-id: emaillist
                  client-secret: XQklyMSQ5l2wmKK8wuoa0aV5Os5M2fY1
                  scope: [ openid, profile, email ]
                  authorization-grant-type: authorization_code
                  redirect-uri: "http://localhost:8888/api/emaillist/oauth2/code/{registrationId}"
            provider:
                keyclock:
                   authorization-uri: http://localhost:5555/realms/poscodx2023-realm/protocol/openid-connect/auth
                   token-uri: http://localhost:5555/realms/poscodx2023-realm/protocol/openid-connect/token
                   issuer-uri: http://localhost:5555/realms/poscodx2023-realm
                   user-name-attribute: preferred_username
                      